name: rebeal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animate_do: ^4.2.0
  awesome_icons: ^1.1.0
  cached_network_image: ^3.2.3
  camera: ^0.11.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^12.0.2
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  get_it: ^8.2.0
  iconsax: ^0.0.8
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  path: ^1.8.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  share_plus: ^12.0.0
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
